#!/bin/bash
# =============================================================================
# [R.306] DRIVER -- runs one stage's job list on a fixed-size worker pool.
#
#   usage: scripts/r306_drive.sh <STAGE>        # A | B | C | D
#
# Job file format (one cell per line, generated by scripts/r306_plan.py):
#     <label>\t<seed>\t<args>
#
# ⛔ TRAPS THIS AVOIDS
#  T1 [R.303] every cell writes its OWN csv, keyed by label, and stage-D labels
#     carry the seed -- `_upsert_result`'s key omits `seed`, so N seeds in one
#     CSV silently collapse to the last.  scripts/r304_upsert_gate.py enforces.
#  T2 [R.141] a `.failed` marker is NEVER a wait condition; failures are
#     recorded for diagnosis and simply re-run on resume.
#  T3 [R.194 5] the job count uses the ONLY pgrep recipe verified on this box;
#     an unanchored pgrep matches the shell itself and over-counts.
#  T4 [R.209] an 8th concurrent job inflates every running cell ~2.2x, and
#     CONTEXT 1 pins this box to cuda:0 with cuda:1 left free.
#  T5 mkdir-based claiming is safe across workers AND across a driver relaunch.
# =============================================================================
set -u
cd /workspace/lora_research_signal || exit 1

STAGE=${1:?usage: r306_drive.sh <A|B|C|D>}
D=scratchpad/phaseR/r306
mkdir -p "$D"/{csv,logs,done,claim,failed}

JOBS="$D/jobs_${STAGE}.tsv"
[ -s "$JOBS" ] || { echo "[r306] no jobs for stage $STAGE"; exit 0; }

WORKERS=${R306_WORKERS:-3}
export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}   # CONTEXT 1: cuda:0 only

COMMON="--model_name_or_path roberta-base --task_name rte --dtype float32 \
 --adapter_target_modules query,value --per_device_train_batch_size 32 \
 --num_train_epochs 30 --num_warmup_steps 140"

TOTAL=$(wc -l < "$JOBS")
njobs() { pgrep -af 'src/train_glue.py' | grep -c '^[0-9]\+ env/bin/python'; }

worker() {
  local wid=$1
  while IFS=$'\t' read -r label seed args; do
    [ -z "${label:-}" ] && continue
    [ -f "$D/done/$label" ] && continue
    mkdir "$D/claim/$label" 2>/dev/null || continue
    local t0 n0 rc dt
    t0=$(date +%s); n0=$(njobs)
    GLUE_SEEDS=$seed GLUE_RESULTS_FILE="$D/csv/$label.csv" \
      env/bin/python -u src/train_glue.py $COMMON $args --name "$label" \
      > "$D/logs/$label.log" 2>&1
    rc=$?
    dt=$(( $(date +%s) - t0 ))
    # A cell is COMPLETE only if it exited clean AND wrote its results row --
    # the row lands after the final epoch, so its presence IS the completion
    # check (PROCESS.md 1.4).  A `.done` marker on a partial run is [R.289]'s
    # "don't quote partial work" defect made permanent.
    if [ $rc -eq 0 ] && [ -s "$D/csv/$label.csv" ]; then
      touch "$D/done/$label"
      echo "[r306][$STAGE][w$wid] OK   $label  ${dt}s  njobs_at_start=$n0  $(date +%T)"
    else
      echo "rc=$rc dt=${dt}s $(date +%T)" > "$D/failed/$label"
      rmdir "$D/claim/$label" 2>/dev/null
      echo "[r306][$STAGE][w$wid] FAIL $label  rc=$rc  ${dt}s  $(date +%T)" >&2
    fi
    echo "[r306][$STAGE] progress $(ls "$D/done" 2>/dev/null | wc -l) done overall"
  done < "$JOBS"
}

echo "[r306] stage $STAGE: $TOTAL cells, $WORKERS workers, live jobs now $(njobs), $(date +%F' '%T)"
for w in $(seq 1 "$WORKERS"); do worker "$w" & done
wait

NDONE=0
while IFS=$'\t' read -r label _ _; do
  [ -f "$D/done/$label" ] && NDONE=$((NDONE+1))
done < "$JOBS"
echo "[r306] stage $STAGE EXIT  done=${NDONE}/${TOTAL}  $(date +%F' '%T)"
[ "$NDONE" -eq "$TOTAL" ]
