#!/bin/bash
# =============================================================================
# [R.310] DRIVER -- runs ONE task's cell list on a fixed-size worker pool.
#
#   usage: scripts/r310_drive.sh <TASK>     # cb|mrpc|stsb|cola|boolq|sst2|mnli
#
# Job file format (one cell per line, generated by scripts/r310_plan.py):
#     <label>\t<seed>\t<args>
# ⭐ Unlike [R.305]'s driver there is NO shared COMMON string here: the protocol
# is PER TASK (each task's own warmup), so the planner writes the complete arg
# string into the job line.  A COMMON constant in this file would be a second
# place for the protocol to live, and the two would drift.
#
# ⛔ TRAPS THIS AVOIDS
#  T1 [R.303] every cell writes its OWN csv and the label carries the seed --
#     `_upsert_result`'s key omits `seed`, so N seeds in one CSV collapse to the
#     last.  scripts/r304_upsert_gate.py enforces it.
#  T2 [R.141] a `.failed` marker is NEVER a wait condition; failures are recorded
#     for diagnosis and simply re-run on resume.
#  T3 [R.194] the job count uses the ONLY pgrep recipe verified on this box.
#  T4 [R.209] an 8th concurrent job inflates every running cell ~2.2x, and
#     CONTEXT §5 pins this box to cuda:0 with cuda:1 LEFT FREE.
#  T5 mkdir-based claiming is safe across workers AND across a driver relaunch.
#  T6 completion requires rc==0 AND a non-empty CSV.  The results row lands after
#     the final epoch, so its presence IS the completion check -- a `.done`
#     marker on a partial run is [R.289]'s defect made permanent.  At 30 epochs
#     on MNLI a cell is ~66 h, so this matters more here than anywhere prior.
# =============================================================================
set -u
cd /workspace/lora_research_signal || exit 1

TASK=${1:?usage: r310_drive.sh <cb|mrpc|stsb|cola|boolq|sst2|mnli>}
D=scratchpad/phaseR/r310
mkdir -p "$D"/{csv,logs,done,claim,failed}

JOBS="$D/jobs_${TASK}.tsv"
[ -s "$JOBS" ] || { echo "[r310] no jobs for task $TASK"; exit 0; }

WORKERS=${R310_WORKERS:-3}
export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}   # CONTEXT §5: cuda:0 only

TOTAL=$(wc -l < "$JOBS")
njobs() { pgrep -af 'src/train_glue.py' | grep -c '^[0-9]\+ env/bin/python'; }

worker() {
  local wid=$1
  while IFS=$'\t' read -r label seed args; do
    [ -z "${label:-}" ] && continue
    [ -f "$D/done/$label" ] && continue
    mkdir "$D/claim/$label" 2>/dev/null || continue
    local t0 n0 rc dt
    t0=$(date +%s); n0=$(njobs)
    echo "[r310][$TASK][w$wid] START $label  njobs_at_start=$n0  $(date +%F' '%T)"
    GLUE_SEEDS=$seed GLUE_RESULTS_FILE="$D/csv/$label.csv" \
      env/bin/python -u src/train_glue.py $args --name "$label" \
      > "$D/logs/$label.log" 2>&1
    rc=$?
    dt=$(( $(date +%s) - t0 ))
    if [ $rc -eq 0 ] && [ -s "$D/csv/$label.csv" ]; then
      touch "$D/done/$label"
      echo "[r310][$TASK][w$wid] OK   $label  ${dt}s  $(date +%T)"
    else
      echo "rc=$rc dt=${dt}s $(date +%T)" > "$D/failed/$label"
      rmdir "$D/claim/$label" 2>/dev/null
      echo "[r310][$TASK][w$wid] FAIL $label  rc=$rc  ${dt}s  $(date +%T)" >&2
    fi
    echo "[r310][$TASK] progress $(ls "$D/done" 2>/dev/null | wc -l) cells done overall"
  done < "$JOBS"
}

echo "[r310] task $TASK: $TOTAL cells, $WORKERS workers, live jobs now $(njobs), $(date +%F' '%T)"
for w in $(seq 1 "$WORKERS"); do worker "$w" & done
wait

NDONE=0
while IFS=$'\t' read -r label _ _; do
  [ -f "$D/done/$label" ] && NDONE=$((NDONE+1))
done < "$JOBS"
echo "[r310] task $TASK EXIT  done=${NDONE}/${TOTAL}  $(date +%F' '%T)"
[ "$NDONE" -eq "$TOTAL" ]
